name: Publish And Deploy Demo # 自动部署的名称

on:
  push:
    branches:
      - main
    paths:
      - ".github/release.json"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Read tag_main
      id: tag_main
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        path: ./.github/release.json
        property: tag_main

    - name: Read tag_latest
      id: tag_latest
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
        path: ./.github/release.json
        property: tag_latest

    - name: Read description
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/release.info

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sh /usr/local/sms/restartweb.sh
